DROP DATABASE IF EXISTS FEC;

CREATE DATABASE FEC;

USE FEC;

CREATE TABLE products (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item VARCHAR(200) NOT NULL
);

CREATE TABLE productReviews (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  reviewer VARCHAR(200) NOT NULL,
  title VARCHAR(200) NOT NULL,
  rating FLOAT NOT NULL,
  content VARCHAR(500) NOT NULL,
  helpful INT NOT NULL,
  avatar VARCHAR(200) NOT NULL,
  product_id INT NOT NULL
);

CREATE TABLE sellerReviews (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rating FLOAT NOT NULL,
  sellDate VARCHAR(200) NOT NULL,
  content VARCHAR(255) NOT NULL,
  product_id INT NOT NULL,
  reviewer VARCHAR(200) NOT NULL,
  FOREIGN KEY (product_id) REFERENCES products(id)
);
